version: "3.7"
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-container
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      #KAFKA_CREATE_TOPICS: "page-scraper:2:1,funding-extractor:1:1,validation:1:1,news-processor:1:1,to-db-insertor1:1:1,to-db-insertor2:1:1"
      KAFKA_CREATE_TOPICS: "domain:3:1"


    #faust-service:
    #  build:
    #    context: ./faust-app
    #  container_name: faust-app
    #  depends_on:
    #    - kafka
    #  restart: on-failure
    #  ports:
    #    - "6066:6066"
    #  environment:
    #    - "KAFKA_CONNECT=kafka:9092"

    #producer-consumer-service:
    #  build:
    #    context: ./producer-consumer
    #  container_name: producer-consumer
    #  depends_on:
    #    - faust-service
    #  restart: on-failure
    #  environment:
    #    - "KAFKA_CONNECT=kafka:9092"
    #schema-registry:
    #  image: confluentinc/cp-schema-registry:5.1.0
    #  depends_on:
    #    - kafka
    #    - zookeeper
    #  environment:
    #    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    #    SCHEMA_REGISTRY_HOST_NAME: schema-registry
    #    SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    #  ports:
    #    - "8081:8081"


  akhq:
    image: tchiotludo/akhq
    environment:
      JVM_OPTS_FILE: /app/jvm.options
    ports:
      - "8082:8080"
    volumes:
      - ./akhq-config-test.yml:/app/application.yml
    depends_on:
      - kafka
      #- schema-registry
    restart: always